[package]
name = "vanity-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
ed25519-dalek = { version = "1", features = ["rand"] }
rand = "0.7"
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
bs58 = "0.5"
js-sys = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
